debug: true
healthcheck: true

mqtt:
  base_topic: rfxcom2mqtt
  server: tcp://<IP ADDRESS>
  username: <USERNAME>
  password: <PASSWORD>
  qos: 0
  retain: false

rfxcom:
  usbport: /dev/ttyUSB0
  debug: false
  transmit:
    repeat: 4
    lighting1:
      - X10
      - ARC
      - ELRO
      - PHILIPS_SBC
    lighting2:
      - AC
      - HOMEEASY_EU
    lighting3:
      - KOPPLA
    lighting4:
      - PT2262
  receive:
    - temperaturehumidity1
    - homeconfort
    - lighting1
    - lighting2
    - lighting3
    - lighting4
    - remote
    - security1

devices:
  - id: '0x5C02'
    title: 'Bathroom Temp & Hum'

  - id: '0xB9459A'
    title: 'Garden motion'

  - id: '1001010/1'
    name: 'CucuDimmer'
    title: 'Kitchen Dimmer Light'
    type: 'lighting2'

  - id: '0x012E00FF'
    name: 'Living Room switch'

  - id: '0x00ED400F'
    name: 'Lights'
    units:
      - unitCode: '1'
        name: 'Light1'
        title: 'Living Room'
      - unitCode: '2'
        name: 'Light2'
        title: 'Kitchen'
      - unitCode: '3'
        name: 'Light3'
        title: 'Garage'
      - unitCode: '4'
        name: 'Light4'
        title: 'Garden'
    type: 'lighting2'

  - id: '0x3D090F'
    name: 'Switch1'
    command: 'on'
    title: 'Living Room Lights on'
    type: 'lighting4'
  - id: '0x3D090E'
    name: 'Switch1'
    command: 'off'
    title: 'Living Room Lights off'
    type: 'lighting4'
