version: "3.8"

services: 
  rfxcom2mqtt:
    image: legobas/rfxcom2mqtt
    container_name: rfxcom2mqtt
    build: /home/legobas/rfxcom2mqtt
    volumes:
      - /home/legobas/data/rfxcom2mqtt:/app/data
    devices:
      - /dev/ttyUSB1:/dev/ttyUSB0
    environment:
      - TZ=Europe/Amsterdam
    restart: unless-stopped
